### ISSUE TITLE
Details about how to partition the MNIST dataset.

### ISSUE THREAD

**Issue by liyipeng00** [Zoesgithub/FedReg#1]
Thanks for your time to check this issue.

I have checked the paper and the code carefully, yet I can not find the details about how to partition the MNIST dataset, where it only tells us each client has samples from one class or two classes. I also run the example `python main.py -c tasks/mnist/FedReg_e40_lr1_g4/config` in the README.md. The dataset 'data/mnist_10000/data/train/' is not included. Can you provide more details about how to partition the MNIST dataset.

I am very instersted that how to achive the accuracy 0.976 in MNIST (one class) in the original paper.

**Comment by Zoesgithub** [comment]
Thanks for your interest in our work.You can find the data here (https://drive.google.com/file/d/1gFhhCuQIfYDhVxQ5eTftyt1N3Y2O8qZt/view). The mnist data are under data/mnist_10000/ (multiple classes) and data/mnist_10000_sc/ (single class).

**Comment by liyipeng00** [comment]
Thanks very much for providing the data kindly.
